
api_auth_index:
    methods: [GET]
    path: /v1/auth
    controller: PhpLab\Sandbox\User\Api\Controllers\AuthController::index

api_auth_login:
    path: /v1/auth
    methods: [POST]
    controller: PhpLab\Sandbox\User\Api\Controllers\AuthController::login
