api_article_post_index:
    methods: [GET]
    path: /v1/article
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::index

api_article_post_create:
    path: /v1/article
    methods: [POST]
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::create

api_article_post_view:
    methods: [GET]
    path: /v1/article/{id}
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::view
    requirements:
        id: '\d+'

api_article_post_update:
    methods: [PUT]
    path: /v1/article/{id}
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::update
    requirements:
        id: '\d+'

api_article_post_delete:
    methods: [DELETE]
    path: /v1/article/{id}
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::delete
    requirements:
        id: '\d+'

api_article_post_index_options:
    methods: [OPTIONS]
    path: /v1/article
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::options

api_article_post_options:
    methods: [OPTIONS]
    path: /v1/article/{id}
    controller: PhpLab\Sandbox\Bundle\Article\Api\Controller\ArticleController::options
    requirements:
        id: '\d+'
