api_messenger_chat_index:
    methods: [GET]
    path: /v1/messenger-chat
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::index

api_messenger_chat_create:
    path: /v1/messenger-chat
    methods: [POST]
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::create

api_messenger_chat_view:
    methods: [GET]
    path: /v1/messenger-chat/{id}
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::view
    requirements:
        id: '\d+'

api_messenger_chat_update:
    methods: [PUT]
    path: /v1/messenger-chat/{id}
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::update
    requirements:
        id: '\d+'

api_messenger_chat_delete:
    methods: [DELETE]
    path: /v1/messenger-chat/{id}
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::delete
    requirements:
        id: '\d+'

api_messenger_chat_index_options:
    methods: [OPTIONS]
    path: /v1/messenger-chat
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::options

api_messenger_chat_options:
    methods: [OPTIONS]
    path: /v1/messenger-chat/{id}
    controller: PhpLab\Sandbox\Messenger\Api\Controllers\ChatController::options
    requirements:
        id: '\d+'
